## 初识 numpy
numpy 其实就是一个多维的数组对象

In [2]:
import numpy as np

data = [1,2,3,4,5]
n = np.array(data * 10)
print(n)

[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2
 3 4 5 1 2 3 4 5 1 2 3 4 5]


每一个numpy的数组都有一个shape和一个叫dtype的属性

In [3]:
n.shape  # shape表示获取获取到np数组的维度

(50,)

In [6]:
n.dtype    # dtype表示获取到数组的类型

dtype('int64')

## 嵌套序列
定义：由一组等长列表组成的列表

In [14]:
arr = [[1,2,3,4], [1,2,3,4]]
print(arr)
arr2 = np.array(arr)
print(arr2)
print(arr2.ndim)    # ndim 表示外层维度
print(arr2.shape)    # shape 表示完整维度：2行4列

[[1, 2, 3, 4], [1, 2, 3, 4]]
[[1 2 3 4]
 [1 2 3 4]]
2
(2, 4)


## np对数据类型的一个判断
数组中同时有字符串和数字时，np自动把数字转成字符串  
当成员中有1个是float时，np自动把所有数字转成float  
int64 -> float64 -> unicode  

### numpy中数据类型
int类型：int8, int16, int32, int64  
float类型：float16, float32, float64, float128

In [18]:
arr = [['1','2',3,4],[5,6,7,8]]
arr2 = np.array(arr)
print(arr2)
print(arr2.dtype)   # U表示unicode

[['1' '2' '3' '4']
 ['5' '6' '7' '8']]
<U21


In [20]:
arr = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(arr)
print(arr2)
print(arr2.dtype)

[[1 2 3 4]
 [5 6 7 8]]
int64


In [22]:
arr = [[1.1,2,3,4],[5,6,7,8]]
arr2 = np.array(arr)
print(arr2)
print(arr2.dtype)

[[1.1 2.  3.  4. ]
 [5.  6.  7.  8. ]]
float64


## numpy创建指定长度数组

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.empty((2,3,4))

array([[[2.68156159e+154, 2.68156159e+154, 7.41098469e-323,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 2.68156159e+154,
         2.68156159e+154],
        [3.95252517e-323, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]]])

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr = np.array([1.2, 1.6, 1.8, -2.3, -5.8])
print(arr)
print(arr.dtype)
print(arr.astype(np.int32))

[ 1.2  1.6  1.8 -2.3 -5.8]
float64
[ 1  1  1 -2 -5]
