# 矢量化
矢量化：数组不用在编写循环的情况下就可以进行批量运算

## 对应位置相加/减/乘/除

In [3]:
import numpy as np
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr1 + arr2

array([ 6,  8, 10, 12])

In [7]:
arr1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7, 8], [5, 6, 7, 8]])
arr1 + arr2

array([[ 6,  8, 10, 12],
       [ 6,  8, 10, 12]])

In [8]:
arr1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7, 8], [5, 6, 7, 8]])
arr2 - arr1

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [9]:
arr1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7, 8], [5, 6, 7, 8]])
arr1 * arr2

array([[ 5, 12, 21, 32],
       [ 5, 12, 21, 32]])

In [12]:
arr1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7, 8], [5, 6, 7, 8]])
arr1 / arr2
arr2 / arr1

array([[5.        , 3.        , 2.33333333, 2.        ],
       [5.        , 3.        , 2.33333333, 2.        ]])

In [14]:
arr1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
5 * arr1

array([[ 5, 10, 15, 20],
       [ 5, 10, 15, 20]])