# 索引和切片

In [3]:
import numpy as np

arr = np.arange(10)
print(arr)
print(arr[1])
print(arr[4:])

arr[0:4] = 11    # arr[0:4] 叫切片
print(arr)

arr_copy = arr.copy()

[0 1 2 3 4 5 6 7 8 9]
1
[4 5 6 7 8 9]
[11 11 11 11  4  5  6  7  8  9]


## 二维数组访问

In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1[0][1])
print(arr1[0,1])

2
2


## 比较运算

In [13]:
names = np.array(['Tony', 'Jack', 'Robin'])
print(names == 'Tony')    # 把Tony和数组中所有元素挨个比较，返回包含bool值的数组
print((names == 'Tony') & (names == 'Tobin'))
print((names == 'Tony') | (names == 'Tobin'))

[ True False False]
[False False False]
[ True False False]


## 花式索引

In [35]:
arr = np.empty((8,4))
print(arr)
for i in range(8):
    arr[i] = i
print(arr)
# 以一个特定的顺序选取行中的子集，传入一个用于指定顺序的整数列表
# 也可以用负数索引从末尾获取
print(arr[[4,3,0,6]])

[[0.00e+000 4.94e-324 9.88e-324 1.48e-323]
 [1.98e-323 2.47e-323 2.96e-323 3.46e-323]
 [3.95e-323 4.45e-323 4.94e-323 5.43e-323]
 [5.93e-323 6.42e-323 6.92e-323 7.41e-323]
 [7.91e-323 8.40e-323 8.89e-323 9.39e-323]
 [9.88e-323 1.04e-322 1.09e-322 1.14e-322]
 [1.19e-322 1.24e-322 1.28e-322 1.33e-322]
 [1.38e-322 1.43e-322 1.48e-322 1.53e-322]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [4]:
# 把32个元素切成8行4列
arr = np.arange(32).reshape((8,4))
print(arr)
# 参数第2个数组的元素，表示对应行数组的列序号，最后输出一个数组
print(arr[[1,5,7,2],[0,3,1,2]])
# 参数第2个数组中，:表示选择所有列，后面的数组表示列元素的顺序的序号
print(arr[[1,5,7,2]][:,[0,3,1,2]])
# ix_表示对第1个数组中的行，按第2个数组的元素进行列排序
print(arr[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 4 23 29 10]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
