转置就是重塑数组的一种特殊的形式，常用的方法有T和transpose

In [7]:
import numpy as np

arr = np.arange(15).reshape((3,5))
print(arr)
print(arr.transpose())  # transpose表示转置
print(arr.T)    # T也表示转置

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [9]:
arr = np.arange(24).reshape((2,3,4))
print(arr)
print(arr.transpose(1,2,0))  # (1,2,0)表示轴，

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]
