np.where，等于同python中 x if condition else y
np.where 一般用于根据一个数组生成一个新的数组，跟Python中map/reduce等函数类似

In [2]:
import numpy as np

x_arr = np.array([1.1,1.2,1.3])
y_arr = np.array([2.1,2.2,2.3])
condition = np.array([True, False, True])
result = [(x if c else y) for x,y,c in zip(x_arr, y_arr, condition)]   # zip接收的参数是可迭代的对象，用于将对象中对应的元素打包成一个个元组，然后返回由这些元组组成的列表
print(result)
r = np.where(condition, x_arr, y_arr)
print(r)

[1.1, 2.2, 1.3]
[1.1 2.2 1.3]


## 值替换

In [4]:
arr = np.random.randn(4,4)
print(arr)
arr_1 = np.where(arr>0, 2, -2)
print(arr_1)
arr_2 = np.where(arr>0, 2, arr)
print(arr_2)

[[-1.26110803 -0.76542473 -0.89888661 -1.63666201]
 [ 0.91026606  0.31290042  0.80263682 -1.77645402]
 [ 1.75521619 -1.47645299 -2.65917215 -0.97965173]
 [ 0.33191142 -0.63091784  0.4214682  -1.32669636]]
[[-2 -2 -2 -2]
 [ 2  2  2 -2]
 [ 2 -2 -2 -2]
 [ 2 -2  2 -2]]
[[-1.26110803 -0.76542473 -0.89888661 -1.63666201]
 [ 2.          2.          2.         -1.77645402]
 [ 2.         -1.47645299 -2.65917215 -0.97965173]
 [ 2.         -0.63091784  2.         -1.32669636]]
