常用函数：sum, mean, std, argmin, argmax, cumsum

## 对所有元素的运算

In [1]:
import numpy as np

arr = np.random.randn(4,4)
print(arr)

[[ 0.16857901 -0.39509084 -0.2703938  -0.12413009]
 [-1.51936406  0.45328402  0.86144874 -1.56404407]
 [ 1.93184813 -0.26686247 -0.00854456 -0.95332967]
 [ 1.02361682 -0.88375219  0.84527778  0.97355748]]


In [7]:
print(arr.mean())  # 所有值的平均值
print(np.mean(arr))  # 同上

print(arr.sum())  # 所有元素求和
print(arr.std())  # 所有元素求标准差

0.017006264395885373
0.017006264395885373
0.27210023033416597
0.9412077339150186


## 在一个轴上运算

In [8]:
print(arr.mean(axis=1))  # 计算轴1上的平均值
print(arr.sum(0))  # 计算轴0上的和

[-0.15525893 -0.44216884  0.17577786  0.48967497]
[ 1.6046799  -1.09242148  1.42778816 -1.66794635]


## 排序方法

In [9]:
arr = np.random.randn(4)
print(arr)

[ 1.09758384  0.82462318 -0.57499998 -0.73588529]


In [11]:
arr.sort()  # 从小到大
print(arr)

[-0.73588529 -0.57499998  0.82462318  1.09758384]


多维数组排序

In [17]:
arr = np.random.randn(4,4)
print(arr)
#arr.sort(1)  # 传递轴号，按轴排序
#print(arr)
arr.sort()  # 按行排序
print(arr)

[[ 0.10892584  0.98661805  0.05494239  1.1180258 ]
 [ 0.77575378  0.99365116  2.122407   -1.12141645]
 [-0.99871613 -1.35586848 -1.05215599 -0.83224773]
 [-0.82689582  0.07731877  0.61469402  0.60983397]]
[[ 0.05494239  0.10892584  0.98661805  1.1180258 ]
 [-1.12141645  0.77575378  0.99365116  2.122407  ]
 [-1.35586848 -1.05215599 -0.99871613 -0.83224773]
 [-0.82689582  0.07731877  0.60983397  0.61469402]]
