numpy可以读写磁盘上的文本数据和二进制数据
主要用到几个函数：np.save, load, 默认情况下数据是以未压缩的原始二进制格式保存在扩展名为.npy的文件中

In [3]:
import numpy as np

arr = np.arange(10)
print(arr)
np.save('any_array', arr)
np.load('any_array.npy')

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

保存成压缩文件

In [7]:
arr = np.arange(10)
np.savez('any_arr_1', a=arr)  # 保存成压缩文件，数组以关键字参数的形式传入
np.load('any_arr_1.npz')['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

保存成txt文件

In [9]:
arr = np.arange(10)
np.savetxt('any_array.txt', arr, delimiter=',')
np.loadtxt('any_array.txt', delimiter=',')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])